apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "qbittorrent.fullname" . }}
  labels:
    app: {{ include "qbittorrent.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "qbittorrent.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "qbittorrent.name" . }}
    spec:
      containers:
        - name: qbittorrent
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.webuiPort }}
            - containerPort: {{ .Values.torrentPort }}
          env:
            - name: PUID
              value: "{{ .Values.env.PUID }}"
            - name: PGID
              value: "{{ .Values.env.PGID }}"
          volumeMounts:
            - name: root
              mountPath: /data
            - name: config
              mountPath: /config
        - name: gluetun
          image: {{ .Values.vpn.image.repository }}:{{ .Values.vpn.image.tag }}
          imagePullPolicy: {{ .Values.vpn.image.pullPolicy }}
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          envFrom:
            - secretRef:
                name: {{ .Values.vpn.secretName }}
          env:
            - name: VPN_SERVICE_PROVIDER
              value: {{ .Values.vpn.provider }}
            - name: VPN_TYPE
              value: {{ .Values.vpn.type }}
            - name: SERVER_COUNTRIES
              value: {{ .Values.vpn.countries }}
            - name: DOT
              value: {{ .Values.vpn.dot | quote }}
            - name: DNS_ADDRESS
              value: {{ .Values.vpn.dnsAddress | quote }}
            - name: HEALTH_TARGET_ADDRESS
              value: {{ .Values.vpn.healthTargetAddress | quote }}
      volumes:
        - name: root
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.root.existingClaim }}
        - name: config
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.config.existingClaim }}

