{{- if .Values.exporter.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "qbittorrent.fullname" . }}-exporter
  labels:
    app: {{ include "qbittorrent.name" . }}
type: Opaque
stringData:
  QBITTORRENT_USER: {{ .Values.secrets.exporter.data.user | quote }}
  QBITTORRENT_PASS: {{ .Values.secrets.exporter.data.password | quote }}
{{- end }}

