apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "ntfy.fullname" . }}
  labels:
    {{- include "ntfy.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "ntfy.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "ntfy.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "ntfy.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "ntfy.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        {{- include "common.restore.initContainer" (dict "Values" .Values "AppName" "ntfy" "ConfigPath" "/var/cache/ntfy") | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["serve"]
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: config
              mountPath: /etc/ntfy/server.yml
              subPath: server.yml
              readOnly: true
            - name: cache
              mountPath: {{ .Values.persistence.cache.mountPath }}
            {{- if .Values.persistence.restore.enabled }}
            - name: {{ if eq .Values.persistence.restore.existingClaim .Values.persistence.backup.existingClaim }}backup{{ else }}restore{{ end }}
              mountPath: {{ .Values.persistence.restore.mountPath }}
              {{- if .Values.persistence.restore.readOnly }}
              readOnly: true
              {{- end }}
            {{- end }}
            {{- if .Values.persistence.backup.enabled }}
            - name: backup
              mountPath: {{ .Values.persistence.backup.mountPath }}
              {{- if .Values.persistence.backup.readOnly }}
              readOnly: true
              {{- end }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        {{- include "common.backup.sidecar" (dict "Values" .Values "AppName" "ntfy" "ConfigPath" "/var/cache/ntfy") | nindent 8 }}
      volumes:
        - name: config
          configMap:
            name: {{ include "ntfy.fullname" . }}
        - name: cache
        {{- if eq .Values.persistence.cache.type "emptyDir" }}
          emptyDir: {}
        {{- else }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.cache.existingClaim }}
        {{- end }}
        {{- if and .Values.persistence.restore.enabled (ne .Values.persistence.restore.existingClaim .Values.persistence.backup.existingClaim) }}
        - name: restore
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.restore.existingClaim }}
        {{- end }}
        {{- if .Values.persistence.backup.enabled }}
        - name: backup
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.backup.existingClaim }}
        {{- end }}
