apiVersion: v2
name: shelfmark
description: A Helm chart for Shelfmark
type: application

dependencies:
  - name: common
    version: 0.1.0
    repository: file://../common

version: 0.1.0
appVersion: "latest"

