apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent
  labels:
    app: qbittorrent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qbittorrent
  template:
    metadata:
      labels:
        app: qbittorrent
    spec:
      containers:
      - name: qbittorrent
        image: linuxserver/qbittorrent:latest
        ports:
        - containerPort: 8080
        - containerPort: 6881
        env:
        - name: WEBUI_PORT
          value: "8080"
        - name: WEBUI_ADMIN_USERNAME
          value: "admin"
        - name: WEBUI_ADMIN_PASSWORD
          value: "tuviejaentanga"
        volumeMounts:
        - name: root
          mountPath: /data
        # securityContext:
        #   runAsUser: 911    # Adjust this UID if necessary
        #   runAsGroup: 911   # Adjust this GID if necessary
      volumes:
      - name: root
        persistentVolumeClaim:
          claimName: nfs-pvc
