apiVersion: v1
kind: Service
metadata:
  name: {{ include "retrom.fullname" . }}
  labels:
    {{- include "retrom.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.webClient }}
      targetPort: web-client
      protocol: TCP
      name: web-client
    - port: {{ .Values.service.other }}
      targetPort: other
      protocol: TCP
      name: other
  selector:
    {{- include "retrom.selectorLabels" . | nindent 4 }}
