# Default values for audiobookshelf.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ghcr.io/advplyr/audiobookshelf
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

webuiPort: 80

persistence:
  data:
    enabled: true
    existingClaim: nas-pvc
  config:
    enabled: true
    type: emptyDir
  restore:
    enabled: true
    existingClaim: nas-config-pvc
    mountPath: /restore-source
    readOnly: true
  backup:
    enabled: true
    existingClaim: nas-config-pvc
    mountPath: /backup-dest
    readOnly: false

ingress:
  enabled: true
  className: nginx
  host: audiobookshelf.localhome.com
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/service-upstream: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  tls:
    - secretName: localhome-tls
      hosts:
        - audiobookshelf.localhome.com

env:
  PUID: "911"
  PGID: "911"
  TZ: "Europe/Amsterdam"

# This is for the secrets for pulling an image from a private repository more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
imagePullSecrets: []
  # - name: regcred
# This is to override the chart name.
nameOverride: ""
fullnameOverride: ""

# This section builds out the service account more information can be found here: https://kubernetes.io/docs/concepts/security/service-accounts/
serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

# This is for setting Kubernetes Annotations to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "80"
  prometheus.io/path: "/metrics"

# Autoscaling configuration
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

