apiVersion: v1
kind: Service
metadata:
  name: {{ include "appflowy.fullname" . }}-cloud
  labels:
    {{- include "appflowy.labels" . | nindent 4 }}
    app.kubernetes.io/component: cloud
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
  selector:
    app: {{ include "appflowy.name" . }}-cloud
