apiVersion: v1
kind: Service
metadata:
  name: {{ include "appflowy.fullname" . }}-minio
  labels:
    {{- include "appflowy.labels" . | nindent 4 }}
    app.kubernetes.io/component: minio
spec:
  type: ClusterIP
  ports:
    - name: api
      port: 9000
      targetPort: 9000
    - name: console
      port: 9001
      targetPort: 9001
  selector:
    app: {{ include "appflowy.name" . }}-minio
