apiVersion: v1
kind: Service
metadata:
  name: {{ include "appflowy.fullname" . }}-postgres
  labels:
    {{- include "appflowy.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: {{ include "appflowy.name" . }}-postgres
