apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "appflowy.fullname" . }}-redis
  labels:
    {{- include "appflowy.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  serviceName: {{ include "appflowy.fullname" . }}-redis
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "appflowy.name" . }}-redis
  template:
    metadata:
      labels:
        app: {{ include "appflowy.name" . }}-redis
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "appflowy.serviceAccountName" . }}
      containers:
        - name: redis
          image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
          ports:
            - containerPort: 6379
          resources:
            {{- toYaml .Values.redis.resources | nindent 12 }}
          readinessProbe:
            exec:
              command: ["redis-cli", "ping"]
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            exec:
              command: ["redis-cli", "ping"]
            initialDelaySeconds: 15
            periodSeconds: 20
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
