apiVersion: v1
kind: Secret
metadata:
  name: {{ include "appflowy.secretName" . }}
  labels:
    {{- include "appflowy.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.secrets.postgres.data.password | quote }}
  DATABASE_URL: {{ printf "postgres://%s:%s@%s-postgres:5432/%s" .Values.postgres.user .Values.secrets.postgres.data.password (include "appflowy.fullname" .) .Values.postgres.database | quote }}
  MINIO_ROOT_USER: {{ .Values.secrets.minio.data.rootUser | quote }}
  MINIO_ROOT_PASSWORD: {{ .Values.secrets.minio.data.rootPassword | quote }}
  GOTRUE_JWT_SECRET: {{ .Values.secrets.gotrue.data.jwtSecret | quote }}
  GOTRUE_ADMIN_EMAIL: {{ .Values.secrets.gotrue.data.adminEmail | quote }}
  GOTRUE_ADMIN_PASSWORD: {{ .Values.secrets.gotrue.data.adminPassword | quote }}
