apiVersion: v1
kind: Service
metadata:
  name: {{ include "ftp-server.fullname" . }}
  labels:
    {{- include "ftp-server.labels" . | nindent 4 }}
  annotations:
    metallb.universe.tf/allow-shared-ip: "ftp-server"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ftpPort | default 21 }}
      targetPort: 21
      protocol: TCP
      name: ftp
    {{- $start := int .Values.service.passivePortStart }}
    {{- $end := int .Values.service.passivePortEnd }}
    {{- range $i := until (add (sub $end $start) 1 | int) }}
    - port: {{ add $start $i }}
      targetPort: {{ add $start $i }}
      protocol: TCP
      name: passive-{{ $i }}
    {{- end }}
  selector:
    {{- include "ftp-server.selectorLabels" . | nindent 4 }}

