apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "ftp-server.fullname" . }}
  labels:
    {{- include "ftp-server.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "ftp-server.fullname" . }}
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "ftp-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "ftp-server.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "ftp-server.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: ftp
              containerPort: 21
              protocol: TCP
            {{- $start := int .Values.service.passivePortStart }}
            {{- $end := int .Values.service.passivePortEnd }}
            {{- range $i := until (add (sub $end $start) 1 | int) }}
            - name: passive-{{ $i }}
              containerPort: {{ add $start $i }}
              protocol: TCP
            {{- end }}
          env:
            - name: USERS
              value: "{{ .Values.env.USERS }}"
            - name: ADDRESS
              value: "{{ .Values.env.ADDRESS }}"
            - name: MIN_PORT
              value: "{{ .Values.env.MIN_PORT }}"
            - name: MAX_PORT
              value: "{{ .Values.env.MAX_PORT }}"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: ftp-data
              mountPath: {{ .Values.persistence.data.mountPath | default "/home/ftpuser" }}
      volumes:
        - name: ftp-data
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.data.existingClaim }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

