apiVersion: v1
kind: Service
metadata:
  name: {{ include "jellyseerr.fullname" . }}
  labels:
    {{- include "jellyseerr.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.servicePort }}
      targetPort: service-port
      protocol: TCP
      name: service-port
  selector:
    {{- include "jellyseerr.selectorLabels" . | nindent 4 }}
