apiVersion: v1
kind: Secret
metadata:
  name: {{ include "configarr.fullname" . }}-secret
  labels:
    {{- include "configarr.labels" . | nindent 4 }}
type: Opaque
stringData:
  secrets.yml: |
    # API Keys for *arr services
    # Loaded from SOPS encrypted secrets.yaml
    
    {{- if .Values.config.sonarr.enabled }}
    SONARR_API_KEY: {{ .Values.secrets.configarr.data.sonarr | quote }}
    {{- end }}
    
    {{- if .Values.config.radarr.enabled }}
    RADARR_API_KEY: {{ .Values.secrets.configarr.data.radarr | quote }}
    {{- end }}
    
    {{- if .Values.config.lidarr.enabled }}
    LIDARR_API_KEY: {{ .Values.secrets.configarr.data.lidarr | quote }}
    {{- end }}
