{{- if .Values.tls }}
{{- if .Values.tls.localhome }}
{{- $namespaces := list "default" "factorio" "turing-pi-dev" }}
{{- range $namespaces }}
---
apiVersion: v1
kind: Secret
metadata:
  name: localhome-tls
  namespace: {{ . }}
type: kubernetes.io/tls
data:
  tls.crt: {{ $.Values.tls.localhome.crt | b64enc }}
  tls.key: {{ $.Values.tls.localhome.key | b64enc }}
{{- end }}
{{- end }}
{{- end }}

