apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "wireshark.fullname" . }}
  labels:
    {{- include "wireshark.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "wireshark.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "wireshark.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "wireshark.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "wireshark.serviceAccountName" . }}
      hostNetwork: {{ .Values.hostNetwork }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- range $key, $val := .Values.env }}
            - name: {{ $key }}
              value: {{ $val | quote }}
            {{- end }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /config
            {{- if .Values.shmSize }}
            - name: dshm
              mountPath: /dev/shm
            {{- end }}
      volumes:
      {{- if .Values.shmSize }}
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: {{ .Values.shmSize }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  {{- if .Values.persistence.config.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: config
      spec:
        accessModes:
          {{- toYaml .Values.persistence.config.accessModes | nindent 10 }}
        resources:
          requests:
            storage: {{ .Values.persistence.config.size }}
        {{- if .Values.persistence.config.storageClassName }}
        storageClassName: {{ .Values.persistence.config.storageClassName }}
        {{- end }}
  {{- end }}
