apiVersion: v1
kind: Service
metadata:
  name: {{ include "wireshark.fullname" . }}
  labels:
    {{- include "wireshark.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.http.port }}
      targetPort: {{ .Values.service.ports.http.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "wireshark.selectorLabels" . | nindent 4 }}
