# Default values for calibre-web.

replicaCount: 1

image:
  repository: linuxserver/calibre-web
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8083

webuiPort: 8083

persistence:
  books:
    enabled: true
    existingClaim: nas-pvc
    mountPath: /books
  config:
    enabled: true
    type: emptyDir
  restore:
    enabled: true
    existingClaim: nas-config-pvc
    mountPath: /restore-source
    readOnly: true
  backup:
    enabled: true
    existingClaim: nas-config-pvc
    mountPath: /backup-dest
    readOnly: false

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/service-upstream: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  hosts:
    - host: calibre-web.localhome.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: localhome-tls
      hosts:
        - calibre-web.localhome.com

env:
  PUID: "1000"
  PGID: "1000"
  TZ: "Europe/Amsterdam"
  # DOCKER_MODS: "linuxserver/calibre-web:calibre" # Optional: for ebook conversion

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

livenessProbe:
  httpGet:
    path: /
    port: 8083
  initialDelaySeconds: 180
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6

readinessProbe:
  httpGet:
    path: /
    port: 8083
  initialDelaySeconds: 60
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6

autoscaling:
  enabled: false
