k3s_cluster:
    children:
        server:
            hosts:
                192.168.2.103: null
        agent:
            hosts:
                192.168.2.101: null
                192.168.2.102: null
                192.168.2.104: null
                192.168.2.105: null
    # Required Vars
    vars:
        ansible_port: 22
        ansible_user: pi
        k3s_version: v1.33.5+k3s1
        # The token should be a random string of reasonable length. You can generate
        # one with the following commands:
        # - openssl rand -base64 64
        # - pwgen -s 64 1
        # You can use ansible-vault to encrypt this value / keep it secret.
        token: ENC[AES256_GCM,data:MsDy2SPNOTF7OSxlnMe/5r7bVbcIKjomZ5qb2wX+V9d1mftMU4uXQSz7Ehr/zZ6vyEO3vKCc1v4wSe1wm8FGBDJYjCB0vh5ManiwMDAkLSJE49Wy/Gojwg==,iv:cUC98WC45VdrVQlVREc7+WkB/0ddOnZTebDG4sJakXw=,tag:YTkfmak5f0LF50SG5jkxBA==,type:str]
        api_endpoint: '{{ hostvars[groups[''server''][0]][''ansible_host''] | default(groups[''server''][0]) }}'
        extra_server_args: --kubelet-arg=image-gc-high-threshold=70 --kubelet-arg=image-gc-low-threshold=50
        extra_agent_args: --kubelet-arg=image-gc-high-threshold=70 --kubelet-arg=image-gc-low-threshold=50
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jsd2g7m3vkh629cged87fvvetsuzv8dalkv38ykpqmyqrkpqmymsr62hqr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByc3ZwNU9IUGdBd2hLTklh
            VXZoUnlQYkJ6TlBmZ1ZSRW11NFJUUkdsLzBVCkd6a1JRR2dtTWhGZjhCWEozbEZW
            cU16STFsOTFxWStMTlRPYThKVE1pYlEKLS0tIHpxOElsN2pRK2lzdyttUjhhWGZr
            clBmbEdqeXNqMFdoMVAwM01nQklWQVUKFcojdFhhp+8smbkSJ/jgvDuDrQbHckGZ
            9WFeDVz1AfCPNxHYDJ6IkCZLg3Ntgdq4ymf+YAy8pwk+VYmIXAjk6g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-18T12:14:56Z"
    mac: ENC[AES256_GCM,data:LDLRorZlix91rv0S5Uv5VhdVkq3Gst8bRBSOZN5TvFKDvB/So6AJXe8mMXpdoJ7S2LiQm5PIzRMJ5OSRj9qSGmB7+fe0Y9kAAp73hwuruX0Iy2dlMh0445+KZCt+gxh6eLneIvUwVCqQH52xT2AtmclWRnkw9baI7J9/WioCeSM=,iv:YLxYwl8bNHPd4H8nKs6LDp5wYxUALdvw0NelhEnwo/c=,tag:vbkImjvN+F2GGY0B9OanKQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|token|username|password|email|game_password|crt|key|FTP_USER_PASS)$
    version: 3.9.0
