{{- if and .Values.secrets .Values.secrets.twingate .Values.secrets.twingate.data }}
apiVersion: v1
kind: Secret
metadata:
  name: twingate-tokens
  labels:
    {{- include "twingate.labels" . | nindent 4 }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  TWINGATE_ACCESS_TOKEN: {{ .Values.secrets.twingate.data.accessToken | quote }}
  TWINGATE_REFRESH_TOKEN: {{ .Values.secrets.twingate.data.refreshToken | quote }}
{{- end }}
