apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "prometheus.fullname" . }}
  labels:
    {{- include "prometheus.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "prometheus.fullname" . }}
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "prometheus.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "prometheus.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "prometheus.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: config-volume
              mountPath: /etc/prometheus/prometheus.yml
              subPath: prometheus.yml
            - name: core-scrape-config
              mountPath: /etc/prometheus/scrape-configs/core-scrape-config.yml
              subPath: core-scrape-config.yml
            - name: kubernetes-discovery-config
              mountPath: /etc/prometheus/scrape-configs/kubernetes-discovery-config.yml
              subPath: kubernetes-discovery-config.yml
            - name: wanderer-production-scrape-config
              mountPath: /etc/prometheus/scrape-configs/wanderer-production-scrape-config.yml
              subPath: wanderer-production-scrape-config.yml
            - name: wanderer-development-scrape-config
              mountPath: /etc/prometheus/scrape-configs/wanderer-development-scrape-config.yml
              subPath: wanderer-development-scrape-config.yml
            {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- if .Values.persistence.enabled }}
            - name: storage-volume
              mountPath: /prometheus
            {{- end }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "prometheus.fullname" . }}-config
        - name: core-scrape-config
          configMap:
            name: {{ include "prometheus.fullname" . }}-core-scrape-config
        - name: kubernetes-discovery-config
          configMap:
            name: {{ include "prometheus.fullname" . }}-kubernetes-discovery-config
        - name: wanderer-production-scrape-config
          configMap:
            name: {{ include "prometheus.fullname" . }}-wanderer-production-scrape-config
        - name: wanderer-development-scrape-config
          configMap:
            name: {{ include "prometheus.fullname" . }}-wanderer-development-scrape-config
        {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- if .Values.persistence.enabled }}
        - name: storage-volume
          persistentVolumeClaim:
            claimName: {{ include "prometheus.fullname" . }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
