apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "huntarr.fullname" . }}
  labels:
    {{- include "huntarr.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "huntarr.fullname" . }}
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "huntarr.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "huntarr.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "huntarr.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: repair-db
          image: keinos/sqlite3:latest
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "Checking for database corruption..."
              if [ -f "/config/huntarr.db" ]; then
                echo "Database found. Attempting integrity check..."
                if sqlite3 /config/huntarr.db "PRAGMA integrity_check;" | grep -q "ok"; then
                  echo "Database is healthy."
                else
                  echo "Database is corrupted! Attempting repair..."
                  mv /config/huntarr.db /config/huntarr.db.bak
                  sqlite3 /config/huntarr.db.bak ".recover" | sqlite3 /config/huntarr.db
                  echo "Repair attempt completed."
                fi
              else
                echo "No database found, skipping repair."
              fi
          volumeMounts:
            - name: config
              mountPath: /config
        {{- include "common.restore.initContainer" (dict "Values" .Values "AppName" "huntarr" "ConfigPath" "/config") | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: HUNTARR_PORT
              value: {{ .Values.service.port | quote }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
            {{- if .Values.persistence.restore.enabled }}
            - name: {{ if eq .Values.persistence.restore.existingClaim .Values.persistence.backup.existingClaim }}backup{{ else }}restore{{ end }}
              mountPath: {{ .Values.persistence.restore.mountPath }}
              {{- if .Values.persistence.restore.readOnly }}
              readOnly: true
              {{- end }}
            {{- end }}
            {{- if .Values.persistence.backup.enabled }}
            - name: backup
              mountPath: {{ .Values.persistence.backup.mountPath }}
              {{- if .Values.persistence.backup.readOnly }}
              readOnly: true
              {{- end }}
            {{- end }}
        {{- include "common.backup.sidecar" (dict "Values" .Values "AppName" "huntarr" "ConfigPath" "/config") | nindent 8 }}
      {{- if .Values.additionalContainers }}
        {{- toYaml .Values.additionalContainers | nindent 8 }}
      {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
        {{- if and .Values.persistence.restore.enabled (ne .Values.persistence.restore.existingClaim .Values.persistence.backup.existingClaim) }}
        - name: restore
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.restore.existingClaim }}
        {{- end }}
        {{- if .Values.persistence.backup.enabled }}
        - name: backup
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.backup.existingClaim }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
