apiVersion: v1
kind: Service
metadata:
  name: {{ include "qbittorrent.fullname" . }}
  labels:
    app: {{ include "qbittorrent.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      name: "web-ui"
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.webuiPort }}
    - protocol: TCP
      name: "torrent-port"
      port: {{ .Values.torrentPort }}
      targetPort: {{ .Values.torrentPort }}
  selector:
    app: {{ include "qbittorrent.name" . }}
