apiVersion: v1
kind: Service
metadata:
  name: {{ include "kube-state-metrics.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kube-state-metrics.labels" . | nindent 4 }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "{{ .Values.service.metricsPort }}"
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http-metrics
      port: {{ .Values.service.metricsPort }}
      targetPort: http-metrics
      protocol: TCP
    - name: telemetry
      port: {{ .Values.service.telemetryPort }}
      targetPort: telemetry
      protocol: TCP
  selector:
    {{- include "kube-state-metrics.selectorLabels" . | nindent 4 }}

