apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "kube-state-metrics.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kube-state-metrics.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "kube-state-metrics.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "kube-state-metrics.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- toYaml .Values.podAnnotations | nindent 8 }}
      labels:
        {{- include "kube-state-metrics.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "kube-state-metrics.serviceAccountName" . }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        fsGroup: 65534
      containers:
        - name: kube-state-metrics
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --port={{ .Values.service.metricsPort }}
            - --telemetry-port={{ .Values.service.telemetryPort }}
          ports:
            - name: http-metrics
              containerPort: {{ .Values.service.metricsPort }}
              protocol: TCP
            - name: telemetry
              containerPort: {{ .Values.service.telemetryPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.service.metricsPort }}
            initialDelaySeconds: 5
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.metricsPort }}
            initialDelaySeconds: 5
            timeoutSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

