apiVersion: v2
name: ftp-server
description: A Helm chart for FTP Server - Exposes Guests folder for friends to download files

# Application chart
type: application

# Chart version
version: 0.1.0

# Pure-FTPd version
appVersion: "latest"

