apiVersion: v1
kind: Secret
metadata:
  name: {{ include "homarr.fullname" . }}-secret
  labels:
    {{- include "homarr.labels" . | nindent 4 }}
type: Opaque
stringData:
  SECRET_ENCRYPTION_KEY: {{ .Values.secrets.homarr.data.encryptionKey | quote }}
